### PR TITLE
Html/css

### PR DESCRIPTION
**Pull request by zeff96**
Added h1 to index.html file,
Added css color property to h1 using external style.css file

### CODE REVIEW

**Review by GedeonTS — CHANGES_REQUESTED** [review]
# STATUS: CHANGES REQUIRED :recycle: :

Hi @zeff96 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights :tophat:  :+1: 
- No linter errors :+1: 
- Good use of GitHub flow :+1: 
## Required Changes ♻️
- [ ] It would be better to write a more descriptive Pull request summary and title, describing all the changes you made to complete this milestone, as it will make your project look more professional.
- [ ] Kindly make sure you use the README template provided by Microverse [here](https://github.com/microverseinc/readme-template) and customize all the fields that are compatible with your current project.


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by Gambit142 — CHANGES_REQUESTED** [review]
Hi @zeff96 👋, 

Great work on making the changes requested by a previous reviewer 👏 

## Highlights
- All linters checks passed ✔️
- Good commit message ✔️ 
- Pull request summary is descriptive ✔️ 

You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.

 ## Required Changes ♻️
### The first reviewer requested that you make your README.md file professional. I am making these suggestions here because I can't highlight the necessary files that will enable me to use the inline comment. Kindly make the following changes to this project:

- [ ] Please make your README.md file look professional by using the recommended template provided by Microverse. Be sure to add the relevant headers that are necessary for this project. 
In the README file, kindly do the following:
- Delete the Microcverse logo or replace it with your logo if you have one 👍 
- Populate information for **_The Future Feature_** section
- Populate information for **_The Key Feature_** Section
- Populate information for **_The Setup_** and **_Usage_** Section (How to clone the repository and open it on a local server)
- The _**MIT**_ section should have a valid LICENSE

You can use the template link provided below to make yours:

https://github.com/microverseinc/readme-template

## Optional suggestions

N/A

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please, remember to tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by zeff96** [comment]
Hi @Gambit142 , I can't see any logo in my project, and I can't generate license.md for this project either

**Review by TuyishimireEric — CHANGES_REQUESTED** [review]
# Status: REQUIRED CHANGES :recycle: 
### Hi  @zeff96    👋 👋 
#### I'm @TuyishimireEric, Your code reviewer,
Good job so far! 🥇 
There are some issues that you still need to work on to go to the next project but you are almost there!


## Highlights 
✔️ Professional PR. 👍
✔️No Linter Error 👍

## Required Changes ♻️

- [ ] **Good job on adding a professional README 👍 👍**
   However, As your PR wants to merge from ```html/css-branch``` to the ```main```, I think it would be better to make all your changes in the ```html/css-branch``` to be more professional

   - And As suggested by the previous Reviewer, Kindly provide a valid link for your project's License 
   NOTE: we recommend using the [MIT license](https://choosealicense.com/licenses/mit/) - you can set it up quickly by [using templates available on GitHub](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository). You can also use [any other license](https://choosealicense.com/licenses/) if you wish.


**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Review by roshan-bajgain — APPROVED** [review]
Hi @zeff96, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- No linter errors. ✔️

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by zeff96** [comment]
@Gambit142  @roshan-bajgain  @GedeonTS @TuyishimireEric, Thanks you all for guiding me step by step, going forward I really feel informed well enough

**Comment by TuyishimireEric** [comment]
Thank you @zeff96 🙏 
Kindly, never merge a PR before being approved by a code reviewer, 
As this PR is already merged, Don't forget to add  ```https://github.com/zeff96/Helo/pull/1``` in your new PR description 👍👍

**Comment by zeff96** [comment]
Greetings.

I only did the merging after it was approved and directed to do the merging

**Pull request merged**
